<a href="https://colab.research.google.com/github/egecandrsn/100_Python_Exercises.ipynb/blob/main/100_Python_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Question: Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints: Consider use range(#begin, #end) method
"""

def is_divisible_by_7_and_not_divisible_by_5():
  divisibles=[]
  for x in range(2000,3200):
    if x % 7 == 0:
      if x % 5 !=0:
        divisibles.append(str(x))
  print(', '.join(divisibles))

is_divisible_by_7_and_not_divisible_by_5()

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199


In [ ]:
"""
Question: Write a program which can compute the factorial of a given numbers.
Suppose the following input is supplied to the program: 8 Then, the output should be: 40320

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
"""

def factorial():
  x=int(input("Give a number: "))
  for i in range(x-1):
    x+=x*i
  print(x)

factorial()

Give a number: 4
24


In [ ]:
"""
Question: Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
Suppose the following input is supplied to the program: 34,67,55,33,12,98
Then, the output should be: ['34', '67', '55', '33', '12', '98'] ('34', '67', '55', '33', '12', '98')

Hints: In case of input data being supplied to the question, it should be assumed to be a console input. tuple() method can convert list to tuple
"""

def list_n_tuple():
  x=input("Give a sequence of numbers seperated with comma: ")
  x=x.split(",")
  x
  y=tuple(x)
  print(x,y)

list_n_tuple()

Give a sequence of numbers seperated with comma: 1,2,3,4,5,6
['1', '2', '3', '4', '5', '6'] ('1', '2', '3', '4', '5', '6')


In [ ]:
"""
Question: Define a class which has at least two methods:
getString: to get a string from console input
printString: to print the string in upper case.
Also please include simple test function to test the class methods.

Hints: Use init method to construct some parameters
"""

class someclass():
  def __init__(self) -> None:
    pass

  def getString(self):
    self.string=input()

  def printString(self):
    print(self.string.upper())

  def simple_test(self):
    test=someclass()
    test.getString()
    test.printString()

some=someclass()
some.simple_test()

qweasdzxc123
QWEASDZXC123


In [ ]:
"""
Question: Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H: C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.
Example Let us assume the following comma separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24

Hints: If the output received is in decimal form, it should be rounded off to its nearest value
(for example, if the output received is 26.0, it should be printed as 26)
In case of input data being supplied to the question, it should be assumed to be a console input.
"""

def Q():

  import math
  Qs=[]
  d=input("Comma separated input sequence to calculate: ")
  d=d.split(",")
  C=50
  H=50
  for i in range(0,len(d)):
    D=int(round(float(d[i])))
    Q=math.sqrt((2*C*D)/H)
    Qs.append(Q)
  return Qs
Q()

Comma separated input sequence to calculate: 123.0,123.232,123


[15.684387141358123, 15.684387141358123, 15.684387141358123]

In [ ]:
"""
Question: Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array.
The element value in the i-th row and j-th column of the array should be i*j. Note: i=0,1.., X-1; j=0,1,¡­Y-1.
Example Suppose the following inputs are given to the program: 3,5 Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]
"""

def two_d_array():

  arrays=[]
  try:
      X = int(input("Enter an integer: "))
      Y = int(input("Enter an second integer: "))
  except ValueError:
      print("Error: Input must be an integer")
  for i in range(X):
    array=[]
    arrays.append(array)
    for j in range(Y):
      array.append(i*j)
  return arrays

two_d_array()

Enter an integer: 12
Enter an second integer: 16


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
 [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45],
 [0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60],
 [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
 [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90],
 [0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105],
 [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120],
 [0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135],
 [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150],
 [0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 121, 132, 143, 154, 165]]

In [ ]:
"""
Question: Write a program that accepts a comma separated sequence of words as input and prints
the words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program: without,hello,bag,world Then, the output should be: bag,hello,without,world

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
"""

def alphabetically():
  x=input("Comma separated sequence of words: ").split(",")
  return sorted(x)

alphabetically()

Comma separated sequence of words: without,hello,bag,world


['bag', 'hello', 'without', 'world']

In [ ]:
"""
Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.
Suppose the following input is supplied to the program: Hello world Practice makes perfect Then, the output should be: HELLO WORLD PRACTICE MAKES PERFECT

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
"""

def capitalize_lines():
  lines=[]
  while True:
    line=input("Sequence of lines to capitalize: ")
    if not line:
      break
    flines.append(line.upper())
  return lines

capitalize_lines()

Sequence of lines to capitalize: sdfsd
Sequence of lines to capitalize: sdfgdgfjghkjg
Sequence of lines to capitalize: 1243565y4rufgjhdfgwiws,fdsd
Sequence of lines to capitalize: sdgdfgjghjrdgsfADSASf
Sequence of lines to capitalize: 


['SDFSD',
 'SDFGDGFJGHKJG',
 '1243565Y4RUFGJHDFGWIWS,FDSD',
 'SDGDFGJGHJRDGSFADSASF']

In [ ]:
"""
Question: Write a program that accepts a sequence of whitespace separated words as input and prints/
the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program: hello world and practice makes perfect and hello world again
Then, the output should be: again and hello makes perfect practice world

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
We use set container to remove duplicated data automatically and then use sorted() to sort the data.
"""

def whitespaced():
  removed=[]
  words=input("A sequence of whitespace separated words: ")
  words=words.split(" ")
  for i in range(len(words)):
    if words[i] not in removed:
      removed.append(words[i])
  return sorted(removed)

whitespaced()

A sequence of whitespace separated words: e32 234w efs fw 3r 43 fw f34 t34 t 34r 34r 34 rr34 f 34


['234w',
 '34',
 '34r',
 '3r',
 '43',
 'e32',
 'efs',
 'f',
 'f34',
 'fw',
 'rr34',
 't',
 't34']

In [ ]:
"""
Question: Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input/
and then check whether they are divisible by 5 or not.
The numbers that are divisible by 5 are to be printed in a comma separated sequence.
Example: 0100,0011,1010,1001 Then the output should be: 1010 Notes: Assume the data is input by console.

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
"""
def four_digit():

  divisibles=[]
  try:
    digits=input("Comma separated 4 digit binary: ")
    digits=digits.split(",")
    for digit in digits:
      digit=int(digit)
      if digit % 5 == 0:
        divisibles.append(digit)
  except:
    raise ValueError("Input must be number, separated with comma")
  return divisibles
four_digit()

Comma separated 4 digit binary: 1010


[1010]

In [ ]:
"""
Question: A website requires the users to input username and password to register.
Write a program to check the validity of password input by users. Following are the criteria for checking the password:

At least 1 letter between [a-z]
At least 1 number between [0-9]
At least 1 letter between [A-Z]
At least 1 character from [$#@]
Minimum length of transaction password: 6
Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria.
Passwords that match the criteria are to be printed, each separated by a comma.
Example If the following passwords are given as input to the program: ABd1234@1,a F1#,2w3E*,2We3345 Then, the output of the program should be: ABd1234@1
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
"""

def pass_control():
  import re
  while True:
    password=input(" Enter a password:\n\n(Press Enter to terminate)")
    if re.search(r'\d+',password):
      if re.search(r'[a-z]',password):
        if re.search(r'[A-Z]',password):
          if re.search(r'[!@#$%^&*()_+\-=\[\]{};:\'",.<>?~]',password):
            if len(password) <12:
              if len(password) > 6:
                print("Password is okay!")
    if not password:
      break

pass_control()

 Enter a password:

(Press Enter to terminate)


In [ ]:
"""
Question: You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers.
The tuples are input by console. The sort criteria is: 1: Sort based on name; 2: Then sort based on age; 3:
Then sort by score. The priority is that name > age > score. If the following tuples are given as input to the program:
Tom,19,80 John,20,90 Jony,17,91 Jony,17,93 Json,21,85 Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

Hints: In case of input data being supplied to the question, it should be assumed to be a console input. We use itemgetter to enable multiple sort keys.
"""

def ascending():

  lists=[]
  from operator import itemgetter, attrgetter
  while True:
    unsorted=input("(name, age, height)\nPress Enter to terminate:")
    if not unsorted:
      break
    unsort=tuple(unsorted.split(","))
    lists.append(unsort)
  print(sorted(lists))

ascending()

(name, age, height)
Press Enter to terminate:Json,21,85
(name, age, height)
Press Enter to terminate:Jony,17,93
(name, age, height)
Press Enter to terminate:Jony,17,91
(name, age, height)
Press Enter to terminate:John,20,90
(name, age, height)
Press Enter to terminate:Tom,19,80
(name, age, height)
Press Enter to terminate:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]


In [ ]:
"""
Question: Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

Hints: Consider use yield
"""
def classs(n:int):

  for i in range(0,n):
    if i %7 == 0:
      yield i

for yiel in classs(100):
    print(yiel)


0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [ ]:
"""
Question: Write a program to compute the frequency of the words from the input.
The output should output after sorting the key alphanumerically.
Suppose the following input is supplied to the program:
New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
Then, the output should be: 2:2 3.:1 3?:1 New:1 Python:5 Read:1 and:1 between:1 choosing:1 or:2 to:1

Hints In case of input data being supplied to the question, it should be assumed to be a console input.
"""

def word_frequency():
  dictionary={}
  words=input("Write anything: ")
  words=words.split(" ")
  words=sorted(words)
  for word in words:
    dictionary[word]=dictionary.get(word,0)+1
  return dictionary
word_frequency()

Write anything: QWE QWE QWE QWE QWE QWE ASD ASD RG RTH TYJH RTG ERGF ERGF ERG RTH TYR JHTY JTY JFG HFGM GR5MY 54M NNKNlken3k4j6n 4n 45tejkt 4kt e4kt wemr qqw eqwewtne ktn54ömt 5öm y554lmy 45lmt 54kjt 45lk 45lg 54lgk 45kjgm 45l 45kjg 45kjg 45kjt 54kg 45kg 45kgn 54kg 45kg 45kg 45kg 45kg 45kg 45kjg 45kjg 54kjg 54kg 45kjg 54kjg 54kjg kj kj kj kj kj 5tr gr gerkg rkgbrtbgk


{'45kg': 6,
 '45kgn': 1,
 '45kjg': 5,
 '45kjgm': 1,
 '45kjt': 1,
 '45l': 1,
 '45lg': 1,
 '45lk': 1,
 '45lmt': 1,
 '45tejkt': 1,
 '4kt': 1,
 '4n': 1,
 '54M': 1,
 '54kg': 3,
 '54kjg': 3,
 '54kjt': 1,
 '54lgk': 1,
 '5tr': 1,
 '5öm': 1,
 'ASD': 2,
 'ERG': 1,
 'ERGF': 2,
 'GR5MY': 1,
 'HFGM': 1,
 'JFG': 1,
 'JHTY': 1,
 'JTY': 1,
 'NNKNlken3k4j6n': 1,
 'QWE': 6,
 'RG': 1,
 'RTG': 1,
 'RTH': 2,
 'TYJH': 1,
 'TYR': 1,
 'e4kt': 1,
 'eqwewtne': 1,
 'gerkg': 1,
 'gr': 1,
 'kj': 5,
 'ktn54ömt': 1,
 'qqw': 1,
 'rkgbrtbgk': 1,
 'wemr': 1,
 'y554lmy': 1}

Exercise: Palindrome Checker

Description:
Write a Python function that checks if a given string is a palindrome. A palindrome is a word, phrase, or sequence of characters that reads the same forward and backward (ignoring spaces, punctuation, and capitalization).

Instructions:

1. Create a Python function called `is_palindrome` that takes a single argument `text`.

2. Inside the function, remove any spaces and convert the entire text to lowercase to make the comparison case-insensitive.

3. Check if the modified `text` is the same when read forward and backward. If it is, return `True`; otherwise, return `False`.

4. Test your function with different inputs, including both palindromes and non-palindromes, to ensure it works correctly.

Example Usage:
```python
print(is_palindrome("racecar"))  # True
print(is_palindrome("Hello, World!"))  # False
print(is_palindrome("A man a plan a canal Panama"))  # True
```

Happy coding!

In [ ]:
def is_palindrome(word):
  word = word.lower().replace(" ", "").replace(".", "").replace(",", "")
  if word == word[::-1]:
    print(f"Word: {word} is a palindrome!")
  else:
    print("It's not a palindrome")
is_palindrome("ey edip danada pide ye")

It's not a palindrome


Exercise Title: "Word Reversal"

Exercise Description:
Write a Python program that takes a sentence as input from the user and reverses the order of words in the sentence. For example, if the user enters "Hello World," the program should output "World Hello."

Instructions:
1. Prompt the user to input a sentence.
2. Use Python's string manipulation functions to split the sentence into words.
3. Reverse the order of the words.
4. Print the reversed sentence.

Sample Input/Output:
Input: "This is a test"
Output: "test a is This"

Challenge:
Modify the program to handle punctuation and whitespace properly. For example, "Hello, World!" should be reversed as "World! Hello,".

In [ ]:
def reversal():
  x=input()
  x=x.split()
  x=x[::-1]
  for word in range(len(x)):
    print(x[word])
reversal()

123123 123 123  124 124 35 yer gs dfsd gdr g dfgh 
dfgh
g
gdr
dfsd
gs
yer
35
124
124
123
123
123123


**Exercise Title: "Treasure Hunt Game"**

**Objective:** Develop a Python program that simulates a treasure hunt game where the player navigates through a grid to find hidden treasures.

**Instructions:**

1. Create a 5x5 grid as the game board.
2. Place a random treasure on the grid.
3. Allow the player to enter coordinates (row and column) to guess the treasure's location.
4. Provide feedback to the player, indicating if they are getting closer or farther from the treasure with each guess.
5. Limit the player to 5 guesses.
6. Display the grid with the player's progress, marking their guesses and the location of the treasure with appropriate symbols.
7. End the game when the player either finds the treasure or runs out of guesses.
8. Display a message to inform the player of the game's outcome (win or lose).

**Additional Challenges (Optional):**

1. Implement a scoring system based on the number of guesses required to find the treasure.
2. Allow the player to choose the grid size and the number of treasures to make the game more challenging.
3. Add obstacles or hazards that the player must avoid while searching for treasure.

**Example Output (Partial):**
```
--- Welcome to the Treasure Hunt Game! ---

Here's the game board:
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]

You have 5 guesses to find the treasure.

Enter your guess (row and column): 2 3

Hmmm... You're getting closer!

Here's the updated board:
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][T]

Enter your guess (row and column): 3 4

Congratulations! You found the treasure! You win!
```

**Note:** Feel free to customize the exercise and add more features to make it even more engaging and challenging for learners.

In [ ]:
def game():
  import numpy
  X=numpy.random.randint(1,6)
  Y=numpy.random.randint(1,6)
  array=numpy.zeros((5,5))
  print("--- Welcome to the Treasure Hunt Game! ---\n\n","Here's the game board:\n",array,"\n\nYou have 5 guesses to find the treasure.\n")
  for i in range(1,6):
    x=input("Enter your guess (row,column): ")
    try:
      x,y=x.split(",")
      x=int(x)
      y=int(y)
    except:
      raise ValueError("Values must seperated with comma!")
    array[x-1,y-1]=i
    print(array)
    if X==x and Y==y:
      print("Congratulations! You found the treasure! You win!")
      break
    elif X==x or Y==y:
      print("Hmmm... You're getting closer!")
    else:
      print("Neither row or column is true.")

In [ ]:
game()

--- Welcome to the Treasure Hunt Game! ---

 Here's the game board:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

You have 5 guesses to find the treasure.

Enter your guess (row,column): 2,3
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Neither row or column is true.
Enter your guess (row,column): 3,4
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Hmmm... You're getting closer!
Enter your guess (row,column): 3,5
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 2. 3.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Neither row or column is true.
Enter your guess (row,column): 5,3
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 2. 3.]
 [0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0.]]
Neither row or column is true.
Enter your guess (row,column): 1,4
[[0. 0. 0. 5. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 2. 3.]
 [0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0.]]
Congratulations! You found the treasure! Y

**Exercise Title:** "Crypto Cipher Challenge"

**Exercise Description:**

In this exercise, you'll practice your Python skills by creating a program that encrypts and decrypts messages using a custom crypto cipher. This cipher involves shifting letters in the alphabet by a certain number of positions.

**Instructions:**

1. Define a function `encrypt(message, shift)` that takes a string `message` and an integer `shift`. This function should shift each letter in the message `shift` positions to the right in the alphabet. For example, if `shift` is 3, 'a' should become 'd', 'b' should become 'e', and so on. Non-alphabet characters should remain unchanged. The function should return the encrypted message.

2. Define a function `decrypt(encrypted_message, shift)` that takes an encrypted message and the same integer `shift` used for encryption. This function should decrypt the message, shifting each letter `shift` positions to the left to recover the original message.

3. Create a sample message, for example, "hello, world!", and an encryption shift of 3.

4. Use your `encrypt` function to encrypt the sample message and store the result.

5. Use your `decrypt` function to decrypt the encrypted message using the same shift value. Verify that the decrypted message matches the original message.

**Example:**

```python
message = "hello, world!"
shift = 3

# Encrypt the message
encrypted_message = encrypt(message, shift)
print("Encrypted Message:", encrypted_message)

# Decrypt the message
decrypted_message = decrypt(encrypted_message, shift)
print("Decrypted Message:", decrypted_message)
```

**Challenge:**

For an extra challenge, you can add error handling to your functions to handle cases where the shift value is negative or greater than 26.

In [ ]:
def encrypt(message,shift):
  enc_message=""
  for m in message:
    if m.isalpha():
      char=chr(((ord(m) - ord('a') + shift) % 26) + ord('a'))
    else:
      char=m
    enc_message+=char
  return enc_message

def decrypt(message, shift):
  dec_message=""
  for m in message:
    if m.isalpha():
      char=chr(((ord(m) - ord('a') - shift) % 26) + ord('a'))
    else:
      char=m
    dec_message+=char
  return dec_message

In [ ]:
decrypt("khoor, zruog!",3)

'hello, world!'